apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: country-info-api
  namespace: country-info
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: country-info-api
  minReplicas: 3
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
