apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: country-info
  namespace: country-info
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: country-info.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: country-info-api
                port:
                  number: 80
