apiVersion: v1
kind: Service
metadata:
  name: country-info-api
  namespace: country-info
spec:
  type: ClusterIP
  selector:
    app: country-info
  ports:
    - name: http
      port: 80
      targetPort: http